version: "3.9"

services:
  backend:
    build: .

    container_name: sports-outdoor-backend

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

    restart: unless-stopped