spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sports_outdoor
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.show-sql=true

logging.level.org.springframework=DEBUG
logging.level.root=DEBUG


jwt.secret=MyVerySecretKeyForJwtAuthenticationOutdoorStore2026
jwt.expiration=86400000
