spring.datasource.url=jdbc:postgresql://localhost:5432/sports_outdoor_prod
spring.datasource.username=postgres
spring.datasource.password=12345

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect